apiVersion: v1
kind: Service
metadata:
  name: victory36-loadbalancer
  namespace: victory36
  labels:
    app: victory36-connection-pool
    classification: diamond-sao
  annotations:
    cloud.google.com/load-balancer-type: "External"
    asoos.cloud/purpose: "victory36-20M-agent-loadbalancer"
    asoos.cloud/max-agents: "20000000"
spec:
  type: LoadBalancer
  selector:
    app: victory36-connection-pool
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
