apiVersion: v1
kind: ServiceAccount
metadata:
  name: victory36-connection-pool
  namespace: victory36
  annotations:
    iam.gke.io/gcp-service-account: victory36-mocoa@api-for-warp-drive.iam.gserviceaccount.com
    asoos.cloud/classification: "diamond-sao"
    asoos.cloud/purpose: "workload-identity-for-victory36"
  labels:
    component: victory36
    classification: diamond-sao
automountServiceAccountToken: true
